Implement CSRF protection
rooseveltframework/roosevelt pull request #1351
Opened 2024-01-22 14:48 UTC by awidener3

Include CSRF protection in Roosevelt applications
- CSRF protection is enabled by default.
- CSRF can only be fully disabled by disabling `express-session` (added with #1341).
- Developers can switch between `full` (default) and `manual`. `manual` allows the dev to specify which routes are protected.
- The README has been updated to educate devs on how to include a CSRF token in their `POST` requests.

2024-01-22 14:49 UTC, awidener3 commented
@kethinov I'm not 100% sold on my decision of using `full` vs. `manual` as configuration options. Any suggestions or thoughts?

2024-03-13 14:01 UTC, kethinov requested changes

2024-03-13 14:01 UTC, kethinov commented on README.md
> +    - To use the default store provided by `express-session`, use `"store": "memorystore"`
change this from `"store": "memorystore"` to `"store": "express-session-default"`

2024-03-13 14:01 UTC, kethinov commented on lib/setExpressConfigs.js
> +      if (process.env.NODE_ENV === 'production') {
let's remove the mode check and do it in all modes

2024-04-03 23:00 UTC, merged